# Generated by Django 5.1 on 2024-10-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validar',
            fields=[
                ('id_validar', models.AutoField(primary_key=True, serialize=False)),
                ('cartao_validar', models.CharField(max_length=255)),
                ('cpf_validar', models.CharField(max_length=255)),
                ('nome_validar', models.CharField(max_length=255)),
                ('codigo_validar', models.CharField(max_length=255)),
                ('data_validar', models.CharField(max_length=255)),
            ],
        ),
    ]
